language: node_js
node_js:
  - "6"
before_script:
  - npm install hexo-cli -g
  - cd themes/tranquilpeak
  - yarn
  - cd ../..
  -
script:
  - hexo g
  
deploy:
  provider: pages
  local_dir: public
  repo: dolikey/gh-pages
  skip_cleanup: true
  github_token: $GIT
  on:
    branch: master
  target_branch: gh-pages
