language: node_js

node_js:
  - "10"

cache:
    apt: true
    directories:
        - node_modules

before_script:
  - npm install hexo-cli -g

script:
  - hexo -v
  - hexo g

deploy:
  provider: pages
  local_dir: public
  repo: dolikey/gh-pages
  skip_cleanup: true
  github_token: $GIT_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  target_branch: gh-pages
